### PR TITLE
Add rpc and SDK authorization

### PR DESCRIPTION
**Pull request by filefilegoadmin**
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/127

### CODE REVIEW

**Comment by filefilegoadmin** [comment]
@connector can you please review ?

**Comment by connector** [comment]
What is the purpose of this?

**Comment by filefilegoadmin** [comment]
We could introspect an access token and decide if a key is unlocked from external app in our case the GUI

**Review by connector — APPROVED** [review]
LGTM

**Pull request merged**
